settings:
  max-billboard-length: 20
  max-player-advertising: 3
  date-format: yyyy-MM-dd kk:mm:ss
my-sql:
  host: localhost
  port: 3306
  username: admin
  password: password
  database: minecraft
  table: billboard