name: BillBoard
description: This plugins allows to add advertisement on a billboard so that everyone can read it. 
version: 0.1
main: me.sd5.billboard.BBMain
commands:
  billboard:
    description: The main BillBoard command.
    usage: |
           /<command> new [message]
    aliases: [bb]